# Stage 1: Build the application
FROM node:22-alpine AS builder

RUN npm install -g pnpm

WORKDIR /app
COPY pnpm-lock.yaml package.json ./

RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm build --outDir build
RUN pnpm prune --production

# Stage 2: Run the application
FROM nginx:1.25.2-alpine3.18
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
