replicaCount: 1

image:
  repository: ghcr.io/aet-devops25/team-oopsops/client
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000
  targetPort: 80

# Any env vars the container needs:
env: []
