replicaCount: 1
image:
  repository: ghcr.io/aet-devops25/team-oopsops/genai-service
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
env:
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: openai-secret
        key: OPENAI_API_KEY
