services:
  document-service:
    image: ghcr.io/aet-devops25/team-oopsops/server/document-service:latest
    build:
      context: ./server
      dockerfile: document-service/Dockerfile
    ports:
      - "8091:8091"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  client:
    image: ghcr.io/aet-devops25/team-oopsops/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:8091}
    depends_on:
      - document-service
    restart: unless-stopped
