services:

  document-service:
    image: ghcr.io/aet-devops25/team-oopsops/server/document-service:latest
    build:
      context: ./server
      dockerfile: document-service/Dockerfile
    ports:
      - "8091:8091"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://document-db:5432/documentdb
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=dev_pass
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  document-db:
    image: postgres:alpine
    container_name: document-db
    environment:
      POSTGRES_DB:       documentdb
      POSTGRES_USER:     dev_user
      POSTGRES_PASSWORD: dev_pass
    ports:
      - "5432:5432"
    volumes:
      - document-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d anonymizationdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  anonymization-service:
    image: ghcr.io/aet-devops25/team-oopsops/server/anonymization-service:latest
    build:
      context: ./server
      dockerfile: anonymization-service/Dockerfile
    ports:
      - "8094:8094"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://anonymization-db:5432/anonymizationdb
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=dev_pass
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8094/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  anonymization-db:
    image: postgres:alpine
    container_name: anonymization-db
    environment:
      POSTGRES_DB:       anonymizationdb
      POSTGRES_USER:     dev_user
      POSTGRES_PASSWORD: dev_pass
    ports:
      - "5433:5432"
    volumes:
      - anonymization-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d anonymizationdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  authentication-service:
    image: ghcr.io/aet-devops25/team-oopsops/server/authentication-service:latest
    build:
      context: ./server
      dockerfile: authentication-service/Dockerfile
    ports:
      - "8092:8092"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  archive-service:
    image: ghcr.io/aet-devops25/team-oopsops/server/archive-service:latest
    build:
      context: ./server
      dockerfile: archive-service/Dockerfile
    ports:
      - "8093:8093"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8093/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
  
  genai-service:
    image: ghcr.io/aet-devops25/team-oopsops/genai-service:latest
    build:
      context: ./genai-service
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  client:
    image: ghcr.io/aet-devops25/team-oopsops/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:8091}
    depends_on:
      - document-service
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL:  admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - document-db
      - anonymization-db
    volumes:
      - pgadmin-data:/var/lib/pgadmin 

volumes:
  document-db-data:
  anonymization-db-data:
  pgadmin-data: