apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.services.genaiService.replicaCount }}
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
        - name: genai-service
          image: "{{ .Values.services.genaiService.image.repository }}:{{ .Values.services.genaiService.image.tag }}"
          imagePullPolicy: {{ .Values.services.genaiService.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: {{ .Values.services.genaiService.targetPort }}
          env:
            {{- range .Values.services.genaiService.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openai.secretName }}
                  key: OPENAI_API_KEY