apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: genai-service
spec:
  selector:
    app: genai-service
  ports:
    - port: {{ .Values.services.genaiService.port }}
      targetPort: {{ .Values.services.genaiService.targetPort }}
      protocol: TCP
  type: {{ .Values.services.genaiService.type }}