replicaCount: 1
image:
  repository: ghcr.io/aet-devops25/team-oopsops/server/authentication-service
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8092
  targetPort: 8092
env: []