apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  test-realm.json: |-
{{ .Files.Get "realms/realm.json" | indent 4 }}
