replicaCount: 1
image:
  repository: ghcr.io/aet-devops25/team-oopsops/server/anonymization-service
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8094
  targetPort: 8094
env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://oopsops-app-postgresql:5432/anonymizationdb
  - name: SPRING_DATASOURCE_USERNAME
    value: dev_user
  - name: SPRING_DATASOURCE_PASSWORD
    value: dev_pass