replicaCount: 1
image:
  repository: ghcr.io/aet-devops25/team-oopsops/server/anonymization-service
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8094
  targetPort: 8094
env: []