apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentication-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: authentication-service
    app.kubernetes.io/instance: {{ .Release.Name }}