apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: oopsops-app
spec:
  selector:
    app: client
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
  type: NodePort
