apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: oopsops-app
spec:
  selector:
    app: server
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30001
      protocol: TCP
  type: NodePort
