apiVersion: v1
kind: Service
metadata:
  name: anonymization-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: anonymization-service
  ports:
  - port: {{ .Values.services.anonymizationService.port }}
    targetPort: {{ .Values.services.anonymizationService.port }}
