apiVersion: apps/v1
kind: Deployment
metadata:
  name: anonymization-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: anonymization-service
spec:
  replicas: {{ .Values.services.anonymizationService.replicas }}
  selector:
    matchLabels:
      app: anonymization-service
  template:
    metadata:
      labels:
        app: anonymization-service
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:alpine
        command:
        - sh
        - -c
        - |
          until pg_isready -h postgres -p 5432 -U $POSTGRES_USER; do
            echo "Waiting for postgres to be ready..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: oopsops-secrets
              key: postgres-user
      containers:
      - name: anonymization-service
        image: {{ .Values.services.anonymizationService.image }}
        ports:
        - containerPort: {{ .Values.services.anonymizationService.port }}
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/anonymizationdb"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: oopsops-secrets
              key: postgres-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oopsops-secrets
              key: postgres-password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.services.anonymizationService.port }}
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.services.anonymizationService.port }}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: {{ .Values.services.anonymizationService.resources.requests.memory }}
            cpu: {{ .Values.services.anonymizationService.resources.requests.cpu }}
          limits:
            memory: {{ .Values.services.anonymizationService.resources.limits.memory }}
            cpu: {{ .Values.services.anonymizationService.resources.limits.cpu }}
      restartPolicy: Always