{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # ── API endpoints ─────────────────────────────────────────────
          - path: /api/v1/documents
            pathType: Prefix
            backend:
              service:
                name: document-service
                port:
                  number: {{ .Values.documentService.service.port }}
          - path: /api/v1/authentication
            pathType: Prefix
            backend:
              service:
                name: authentication-service
                port:
                  number: {{ .Values.authenticationService.service.port }}
          - path: /api/v1/archive
            pathType: Prefix
            backend:
              service:
                name: archive-service
                port:
                  number: {{ .Values.archiveService.service.port }}
          - path: /api/v1/genai
            pathType: Prefix
            backend:
              service:
                name: genai-service
                port:
                  number: {{ .Values.genaiService.service.port }}
          # ── SPA catch-all ────────────────────────────────────────────────
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: {{ .Values.client.service.port }}
{{- end }}
