{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oopsops-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.secretName }}
  {{- end }}
  rules:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        # Document Service
        - path: /api/v1/documents
          pathType: Prefix
          backend:
            service:
              name: document-service
              port: { number: {{ .Values.services.documentService.port }} }
        # Authentication Service
        - path: /api/v1/authentication
          pathType: Prefix
          backend:
            service:
              name: authentication-service
              port: { number: {{ .Values.services.authenticationService.port }} }
        # Keycloak
        - path: /realms
          pathType: Prefix
          backend:
            service:
              name: keycloak
              port:
                number: {{ .Values.services.keycloak.port }}
        - path: /auth
          pathType: Prefix
          backend:
            service:
              name: keycloak
              port:
                number: {{ .Values.services.keycloak.port }}
        # Anonymization Service
        - path: /api/v1/anonymization
          pathType: Prefix
          backend:
            service:
              name: anonymization-service
              port:
                number: {{ .Values.services.anonymizationService.port }}
        # GenAI Service
        - path: /api/v1/genai
          pathType: Prefix
          backend:
            service:
              name: genai-service
              port:
                number: {{ .Values.services.genaiService.port }}
        # Client
        - path: /assets
          pathType: Prefix
          backend:
            service:
              name: client
              port:
                number: {{ .Values.client.port }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: client
              port: { number: {{ .Values.client.port }} }
{{- end }}
