apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: oopsops-monitoring
  labels:
    app.kubernetes.io/name: promtail
spec:
  type: ClusterIP
  ports:
  - port: 9080
    targetPort: 9080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: promtail