replicaCount: 1
image:
  repository: ghcr.io/aet-devops25/team-oopsops/server/document-service
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8091
  targetPort: 8091
env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://oopsops-app-postgresql:5432/documentdb
  - name: SPRING_DATASOURCE_USERNAME
    value: dev_user
  - name: SPRING_DATASOURCE_PASSWORD
    value: dev_pass