apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: team-oops-ops
spec:
  selector:
    app: client
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003
      protocol: TCP
  type: NodePort
