apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: team-oops-ops
spec:
  selector:
    app: client
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
  type: {{ .Values.client.service.type }}