apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
  create-multiple-dbs.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE DATABASE documentdb;
        CREATE DATABASE anonymizationdb;
        CREATE DATABASE authdb;
    EOSQL
  api_url: "https://{{ include "oopsops.ingress.host" . }}"
  