apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
# TODO: Change this later to the actual API URL
  api_url: "https://{{ include \"oopsops.ingress.host\" . }}"
