apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: team-oops-ops
data:
  # TODO: The API URL should be your ingress hostname without the /api path
  api_url: http://localhost:30002
