{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ include "oopsops-app.ingressHost" . }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ include "oopsops-app.ingressHost" . }}
      http:
        paths:
          - path: /api/v1/documents
            pathType: Prefix
            backend:
              service:
                name: document-service
                port: { number: {{ .Values.documentService.service.port }} }
          - path: /api/v1/authentication
            pathType: Prefix
            backend:
              service:
                name: authentication-service
                port: { number: {{ .Values.authenticationService.service.port }} }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port: { number: {{ .Values.client.service.port }} }
{{- end }}
