{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "canteen-ingress"
  namespace: "team-oops-ops"
  {{- $annotations := .Values.ingress.annotations | default dict }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "team-oops-ops.student.k8s.aet.cit.tum.de"
      secretName: "canteen-devops25-tls"
  {{- end }}
  #TODO:fix the host hardcoded values
  rules:
    - host: "team-oops-ops.student.k8s.aet.cit.tum.de"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: {{ .Values.client.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: {{ .Values.server.service.port }}
{{- end }}