apiVersion: v1
kind: Secret
metadata:
  name: oopsops-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgres-user: {{ .Values.postgres.user | b64enc }}
  postgres-password: {{ .Values.postgres.password | b64enc }}
  pgadmin-password: {{ .Values.pgadmin.password | b64enc }}