apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: team-oops-ops
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          env:
            {{- range .Values.server.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}