apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-admin
  labels:
    app.kubernetes.io/name: {{ include "keycloak.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.admin.user | b64enc }}
  password: {{ .Values.admin.password | b64enc }}