apiVersion: v1
kind: Service
metadata:
  name: document-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: documentation-service
spec:
  selector:
    app: document-service
  ports:
  - port: {{ .Values.services.documentService.port }}
    targetPort: {{ .Values.services.documentService.port }}