apiVersion: v1
kind: Service
metadata:
  name: {{ include "genai-service.fullname" . }}
  labels:
{{ include "genai-service.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "genai-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}