apiVersion: v1
kind: Service
metadata:
  name: anonymization-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: anonymization-service
  ports:
    - port: {{ .Values.anonymizationService.service.port }}
      targetPort: {{ .Values.anonymizationService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.anonymizationService.service.type }}