apiVersion: v1
kind: Service
metadata:
  name: archive-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: archive-service
  ports:
    - port: {{ .Values.archiveService.service.port }}
      targetPort: {{ .Values.archiveService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.archiveService.service.type }}