apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: authentication-service
  ports:
    - port: {{ .Values.authenticationService.service.port }}
      targetPort: {{ .Values.authenticationService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.authenticationService.service.type }}