apiVersion: v1
kind: Service
metadata:
  name: document-service
  namespace: oops-ops
spec:
  selector:
    app: document-service
  ports:
    - port: {{ .Values.documentService.service.port }}
      targetPort: {{ .Values.documentService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.documentService.service.type }}