apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: genai-service
  ports:
    - port: {{ .Values.genaiService.service.port }}
      targetPort: {{ .Values.genaiService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.genaiService.service.type }}