apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-service
  namespace: oops-ops
spec:
  replicas: {{ .Values.archiveService.replicaCount }}
  selector:
    matchLabels:
      app: archive-service
  template:
    metadata:
      labels:
        app: archive-service
    spec:
      containers:
        - name: archive-service
          image: "{{ .Values.archiveService.image.repository }}:{{ .Values.archiveService.image.tag }}"
          imagePullPolicy: {{ .Values.archiveService.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: {{ .Values.archiveService.service.targetPort }}
          env:
            {{- range .Values.archiveService.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}