apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.documentService.replicaCount }}
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
        - name: document-service
          image: "{{ .Values.documentService.image.repository }}:{{ .Values.documentService.image.tag }}"
          imagePullPolicy: {{ .Values.documentService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.documentService.service.targetPort }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            {{- range .Values.documentService.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            - name: SPRING_DATASOURCE_USERNAME
              value: "dev_user"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: document-db
                  key: postgres-password