apiVersion: v2
name: oopsops-app
description: A Helm chart for the OopsOps Application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    alias: document-db
    version: 16.0.1
    repository: https://charts.bitnami.com/bitnami
