apiVersion: v2
name: oopsops-app
description: A Helm chart for the OopsOps Application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 12.1.6   
    repository: https://charts.bitnami.com/bitnami
