
documentService:
  image:
    repository: ghcr.io/aet-devops25/team-oopsops/server/document-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8091
    targetPort: 8091
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

archiveService:
  image:
    repository: ghcr.io/aet-devops25/team-oopsops/server/archive-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8093
    targetPort: 8093
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

authenticationService:
  image:
    repository: ghcr.io/aet-devops25/team-oopsops/server/authentication-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8092
    targetPort: 8092
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

client:
  image:
    repository: ghcr.io/aet-devops25/team-oopsops/client
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
    targetPort: 80
  replicaCount: 1

genaiService:
  image:
    repository: ghcr.io/aet-devops25/team-oopsops/genai-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  tls: true
  host: use-template-logic
  secretName: "devops25-tls"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"