namespace:
  create: false

server:
  image:
    repository: ghcr.io/oops-ops/server
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8090
    targetPort: 8090
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

client:
  image:
    repository: ghcr.io/oops-ops/client
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
    targetPort: 80
  replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  tls: true
  host: "team-oops-ops.student.k8s.aet.cit.tum.de"
  secretName: "devops25-tls"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"