ingress:
  enabled: true
  className: nginx
  host: redactiq.student.k8s.aet.cit.tum.de
  secretName: devops25-tls
  annotations: {}

postgresql:
  auth:
    username: dev_user
    password: dev_pass
    database: documentdb
  primary:
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

keycloak:
  postgresql:
    enabled: false

  externalDatabase:
    enabled: true
    vendor: POSTGRES
    host: oopsops-postgresql
    port: 5432
    database: authdb
    username: dev_user
    password: dev_pass

  extraEnv: |-
    - name: KEYCLOAK_IMPORT
      value: /opt/keycloak/data/import/realm-config

  realmConfigMapName: realm-config

  ingress:
    enabled: true

  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 600m
      memory: 1Gi

documentService:
  replicaCount: 1
  image:
    repository: ghcr.io/aet-devops25/team-oopsops/server/document-service
    tag:      latest
  service:
    type:       ClusterIP
    port:       8091
    targetPort: 8091
  env: []

authenticationService:
  replicaCount: 1
  image:
    repository: ghcr.io/aet-devops25/team-oopsops/server/authentication-service
    tag:      latest
  service:
    type:       ClusterIP
    port:       8092
    targetPort: 8092
  env: []

anonymizationService:
  replicaCount: 1
  image:
    repository: ghcr.io/aet-devops25/team-oopsops/server/anonymization-service
    tag:      latest
  service:
    type:       ClusterIP
    port:       8094
    targetPort: 8094
  env: []

genaiService:
  replicaCount: 1
  image:
    repository: ghcr.io/aet-devops25/team-oopsops/genai-service
    tag: latest
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  env: []

client:
  replicaCount: 1
  image:
    repository: ghcr.io/aet-devops25/team-oopsops/client
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
    targetPort: 80