apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: {{ .Values.global.namespace }}
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'default-receiver'

    receivers:
      - name: 'default-receiver'
        email_configs:
          - to: 'yosr.nabli@tum.de'
            from: 'alertmanager@redacta.com'
            smarthost: 'smtp.gmail.com:587'
            auth_username: '{{ .Values.alertmanager.email.username }}'
            auth_password: {{ (lookup "v1" "Secret" "oopsops-monitoring" "alertmanager-secret").data.email-auth-password | b64dec | quote }}
            auth_identity: '{{ .Values.alertmanager.email.username }}'
            require_tls: true