apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: {{ .Values.global.namespace }}
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'yosr.nabli99@gmail.com'
      smtp_auth_username: 'yosr.nabli99@gmail.com'
      smtp_auth_password: '/etc/alertmanager/secret/email-auth-password'
      smtp_require_tls: true

    route:
      receiver: 'email-notifications'

    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: 'yosr.nabli@tum.de'
            send_resolved: true