apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    app: alertmanager
