apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeConfig.globalInterval }}
      evaluation_interval: {{ .Values.prometheus.scrapeConfig.evaluationInterval }}

    {{- if .Values.alerting.enabled }}
    rule_files:
      - "/etc/prometheus/rules/*.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    {{- end }}

    scrape_configs:
      # Prometheus self-monitoring
      - job_name: 'prometheus'
        metrics_path: /metrics
        static_configs:
          - targets: ['localhost:9090']

      # All other services will be discovered automatically via ServiceMonitors
      # No manual configuration needed - Rancher's Prometheus Operator handles it