apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeConfig.globalInterval }}
      evaluation_interval: {{ .Values.prometheus.scrapeConfig.evaluationInterval }}

    {{- if .Values.alerting.enabled }}
    rule_files:
      - "/etc/prometheus/rules/*.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    {{- end }}

    scrape_configs:
      # Prometheus self-monitoring
      - job_name: 'prometheus'
        metrics_path: /metrics
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'spring-actuator'
        metrics_path: '/actuator/prometheus'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: '(authentication-service|document-service|anonymization-service)'
            action: keep
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: service

      # All other services will be discovered automatically via ServiceMonitors
      # No manual configuration needed - Rancher's Prometheus Operator handles it