apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerting-rules
  namespace: {{ .Values.global.namespace }}
data:
  system-alerts.yml: |
    groups:
      - name: system
        rules:
          - alert: HighCPUUsage
            expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage on {{`{{ $labels.instance }}`}}"
              description: "CPU usage is above 80% for the last 10min with current value: {{`{{ $value }}`}}%"
          - alert: HighMemoryUsage
            expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
            for: 15m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage on {{`{{ $labels.instance }}`}}"
              description: "Memory usage is above 85% for last 15 minutes with current value: {{`{{ $value }}`}}%"