apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: oopsops-monitoring
  labels:
    app: prometheus


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-target-app
  namespace: oopsops-test
  labels:
    app: prometheus
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs: ["get", "list", "watch"]
---

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-target-app
  namespace: oopsops-test
  labels:
    app: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-target-app
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: oopsops-monitoring
# ---
# # Role for monitoring namespace (your assigned namespace)
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: prometheus
#   namespace: {{ .Values.global.namespace }}
#   labels:
#     app: prometheus
# rules:
#   - apiGroups: [""]
#     resources:
#       - services
#       - endpoints
#       - pods
#       - configmaps
#       - secrets
#       - persistentvolumeclaims
#       - persistentvolumes
#     verbs: ["get", "list", "watch"]
#   - apiGroups:
#       - extensions
#       - networking.k8s.io
#     resources:
#       - ingresses
#     verbs: ["get", "list", "watch"]
#   - apiGroups:
#       - apps
#     resources:
#       - deployments
#       - replicasets
#       - daemonsets
#       - statefulsets
#     verbs: ["get", "list", "watch"]
---
# Role for target application namespace (if different from monitoring namespace)

# RoleBinding for monitoring namespace
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: prometheus
#   namespace: {{ .Values.global.namespace }}
#   labels:
#     app: prometheus
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: prometheus
# subjects:
#   - kind: ServiceAccount
#     name: prometheus
#     namespace: {{ .Values.global.namespace }}
---
# RoleBinding for target application namespace (if different from monitoring namespace)
# {{- if ne .Values.global.namespace .Values.targetApp.namespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-target-app
  namespace: {{ .Values.targetApp.namespace }}
  labels:
    app: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-target-app
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: {{ .Values.global.namespace }}
# {{- end }}