name: Deploy to Rancher Test (PR branches)

on:
  pull_requests:
    branches:
      - '**'

env:
  REPO_OWNER: aet-devops25
  CLIENT_IMAGE: ghcr.io/aet-devops25/team-oopsops/client:latest
  DOCUMENT_IMAGE: ghcr.io/aet-devops25/team-oopsops/server/document-service:latest
  ARCHIVE_IMAGE: ghcr.io/aet-devops25/team-oopsops/server/archive-service:latest
  AUTHENTICATION_IMAGE: ghcr.io/aet-devops25/team-oopsops/server/authentication-service:latest
  GENAI_IMAGE: ghcr.io/aet-devops25/team-oopsops/genai-service:latest
  CLIENT_DIR: ./client
  DOCUMENT_DIR: ./server/document-service
  ARCHIVE_DIR: ./server/archive-service
  AUTHENTICATION_DIR: ./server/authentication-service
  GENAI_DIR: ./genai-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Client Image
        run: |
          docker build -t ${{ env.CLIENT_IMAGE }} ${{ env.CLIENT_DIR }}
          docker push ${{ env.CLIENT_IMAGE }}

      - name: Build and Push Document Service Image
        run: |
          docker build -t ${{ env.DOCUMENT_IMAGE }} -f ${{ env.DOCUMENT_DIR }}/Dockerfile ./server
          docker push ${{ env.DOCUMENT_IMAGE }}

      - name: Build and Push Archive Service Image
        run: |
          docker build -t ${{ env.ARCHIVE_IMAGE }} -f ${{ env.ARCHIVE_DIR }}/Dockerfile ./server
          docker push ${{ env.ARCHIVE_IMAGE }}
      - name: Build and Push Authentication Service Image
        run: |
          docker build -t ${{ env.AUTHENTICATION_IMAGE }} -f ${{ env.AUTHENTICATION_DIR }}/Dockerfile ./server
          docker push ${{ env.AUTHENTICATION_IMAGE }}

      - name: Build and Push GenAI Service Image
        run: |
          docker build -t ${{ env.GENAI_IMAGE }} -f ${{ env.GENAI_DIR }}
          docker push ${{ env.GENAI_IMAGE }}

