name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - 'feat/**'
    paths:
      - 'client/**'
      - 'server/**'
      - '.github/workflows/docker-publish.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Client Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/client:latest ./client
          docker push ghcr.io/${{ github.repository_owner }}/client:latest

      - name: Build and Push Server Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/server:latest ./server
          docker push ghcr.io/${{ github.repository_owner }}/server:latest
