# ABOUTME: This workflow runs tests for the genai-service component on code changes
# ABOUTME: It executes pytest with coverage reporting and validates the Python FastAPI service

name: Test GenAI Service

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'genai-service/**'
      - '.github/workflows/test-genai-service.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'genai-service/**'
  workflow_call:
    secrets:
      OPENAI_API_KEY:
        required: false

jobs:
  test-genai-service:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('genai-service/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: ./genai-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        working-directory: ./genai-service
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANONYMIZATION_SERVICE_URL: "http://mock-service"
        run: |
          ./run_tests.sh

      - name: Generate test summary
        if: always()
        working-directory: ./genai-service
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          if [ -f htmlcov/index.html ]; then
            echo "✅ Tests completed with coverage report generated" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Tests failed or coverage report not generated" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: genai-service-coverage-report
          path: genai-service/htmlcov/
          retention-days: 7

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: genai-service-test-results
          path: genai-service/
          retention-days: 3
